--###################
--## REQUIREMENTS ###
--###################

-- AUTOSTART applications
-- hyprshade -
-- nm-applet (networkmanager service) - network manamenet applet comes with network manager
-- Enpass, Signal Desktop
-- udiskie (+ udisks2 daemon) - for disk managent

-- Run applications (keybinds)
-- browser   = firefox
-- temrinal  = alacritty
-- menu      = rofi
-- calcualtor= qcalculate-gtk
-- files     = thunar

--###############
--## MONITORS ###
--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/
-- monitor=,1920x1080@60,auto,1
hl.monitor({
  output = "",
  mode = "preferred",
  position = "auto",
  scale = "1",
})

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local terminal = "alacritty"
local fileManager = "thunar"
local menu = "rofilauncher"
local browser = "firefox"
local calculator = "qalculate-gtk"

--################
--## AUTOSTART ###
--################

hl.on("hyprland.start", function()
  hl.exec_cmd(
  "/nix/store/99nasl1d5rzdqpkxiszg28ck7g17i24a-dbus-1.14.10/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target")
  hl.exec_cmd("Enpass -minimize")
  hl.exec_cmd("signal-desktop --start-in-tray")
  hl.exec_cmd("nm-applet")
  hl.exec_cmd("udiskie --tray --automount --notify")
  hl.exec_cmd("systemctl --user start hyprpaper")
end)

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/
hl.env("XCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Numix-Cursor")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "Numix-Cursor")

--####################
--## LOOK AND FEEL ###
--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/
-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.device({
  name = "razer-razer-huntsman-tournament-edition-1",
})

local mainMod = "SUPER"

hl.bind(mainMod .. " + SHIFT + q", hl.dsp.window.close())
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + b", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + c", hl.dsp.exec_cmd(calculator))
hl.bind(mainMod .. " + l", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + e", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + SHIFT + f", hl.dsp.window.fullscreen(""))
hl.bind(mainMod .. " + f", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + s", hl.dsp.layout("togglesplit"))
hl.bind("PRINT",
  hl.dsp.exec_cmd("grimblast -n -e 3000 -t png copysave screen -o " ..
    "$HOME" .. "/Pictures/Screenshot/$(date +'%Y-%m-%d-%H%M%S')_screenshot.png"))
hl.bind("CTRL + PRINT", hl.dsp.exec_cmd("grimblast -n -e 3000 -t png copy screen"))
hl.bind("SHIFT + PRINT",
  hl.dsp.exec_cmd("grimblast -n -e 3000 -t png copysave area -o " ..
    "$HOME" .. "/Pictures/Screenshot/$(date +'%Y-%m-%d-%H%M%S')_screenshot.png"))
hl.bind("CTRL + SHIFT + PRINT", hl.dsp.exec_cmd("grimblast -n -e 3000 -t png copy area"))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + CTRL + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + CTRL + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + CTRL + down", hl.dsp.window.move({ direction = "d" }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1, silent = true }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2, silent = true }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3, silent = true }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4, silent = true }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5, silent = true }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6, silent = true }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7, silent = true }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8, silent = true }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9, silent = true }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10, silent = true }))

hl.bind(mainMod .. " + CTRL + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + CTRL + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + CTRL + down", hl.dsp.window.move({ direction = "d" }))

hl.bind("CTRL + ALT + right", hl.dsp.focus({ workspace = "m+1" }))
hl.bind("CTRL + ALT + left", hl.dsp.focus({ workspace = "m-1" }))
hl.bind(mainMod .. " + ALT + right", hl.dsp.focus({ workspace = "+1" }))
hl.bind(mainMod .. " + ALT + left", hl.dsp.focus({ workspace = -1 }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true, repeating = true })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("volume up"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("volume down"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("volume mute"), { locked = true, repeating = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.window_rule({
  match = {
    class = ".*",
  },
  suppress_event = "maximize",
})

hl.window_rule({
  match = {
    class = "^$",
    title = "^$",
    xwayland = 1,
    -- floating = 1,
    fullscreen = 0,
    -- pinned = 0,
  },
  no_focus = true,
})

hl.window_rule({
  match = {
    class = "qalculate-gtk",
  },
  float = true,
})

hl.window_rule({
  match = {
    class = "org.pulseaudio.pavucontrol",
    title = "Volume Control",
  },
  float = true,
})

hl.window_rule({
  match = {
    class = "nm-connection-editor",
  },
  float = true,
})

hl.window_rule({
  match = {
    class = "Enpass title:Enpass Assistant",
  },
  float = true,
})

hl.window_rule({
  match = {
    class = "xdg-desktop-portal-gtk",
  },
  float = true,
})

hl.window_rule({
  match = {
    class = "thunar",
    -- name = "Rename.*", -- TODO: check
  },
  float = true,
  center = true,
  -- focus = true,
})

hl.window_rule({
  match = {
    class = "class:org.pulseaudio.pavucontrol",
  },
  min_size = { 1024, 512 },
})

hl.window_rule({
  match = {
    class = "class:Alacritty",
  },
  opacity = "0.9 override 0.8 override",
})

hl.window_rule({
  match = {
    class = "class:thunar",
  },
  opacity = "0.9 override 0.8 override",
})

hl.config({
  general = {
    gaps_in = 2,
    gaps_out = 2,
    border_size = 4,
    -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col = {
      -- active_border = "rgba(33ccffee) rgba(00ff99ee) 45deg",
      inactive_border = "rgba(595959aa)",
    },
    -- Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true,
    -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false,
    -- layout = "dwindle",
  },
  -- https://wiki.hyprland.org/Configuring/Variables/#decoration
  decoration = {
    rounding = 5,
    -- Change transparency of focused and unfocused windows
    active_opacity = 1.0,
    inactive_opacity = 1.0,
    shadow = {
      enabled = true,
      range = 4,
      render_power = 3,
      color = "rgba(1a1a1aee)",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#blur
    blur = {
      enabled = true,
      size = 3,
      passes = 1,
      vibrancy = 0.1696,
    },
  },
  -- https://wiki.hyprland.org/Configuring/Variables/#animations
  animations = {
    enabled = false,
  },
  -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
  -- dwindle = {
  --   pseudotile = true,     -- # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
  --   preserve_split = true, -- # You probably want this
  -- },
  -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
  master = {
    new_status = "master",
  },
  -- https://wiki.hyprland.org/Configuring/Variables/#misc
  misc = {
    force_default_wallpaper = 0,  --# Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true, --# If true disables the random hyprland logo / anime girl background. :(
    background_color = 0,
  },
  --############
  --## INPUT ###
  --############
  -- https://wiki.hyprland.org/Configuring/Variables/#input
  input = {
    kb_layout = "us,si",
    kb_variant = "",
    kb_model = "",
    kb_options = "caps:swapescape,grp:win_space_toggle",
    kb_rules = "",
    repeat_rate = 50,
    repeat_delay = 180,
    numlock_by_default = true,
    follow_mouse = 1,
    sensitivity = 0, --  # -1.0 - 1.0, 0 means no modification.
    touchpad = {
      natural_scroll = false,
    },
  },
  --##################
  --## KEYBINDINGS ###
  --##################
  -- See https://wiki.hyprland.org/Configuring/Keywords/
  -- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
  -- Move focus with mainMod + arrow keys
  -- Switch workspaces with mainMod + [0-9]
  -- Move active window aorund the workspace/window?
  -- Move active window to a workspace with mainMod + SHIFT + [0-9]
  -- Move left and right the workspaces
  -- Cycle workspaces with same keybind as on gnome
  -- Cycle between used
  -- Cycle between all
  -- Move/resize windows with mainMod + LMB/RMB and dragging
  -- Laptop multimedia keys for volume and LCD brightness
  -- Volume slider up, down, mute with print of output sink and percentage number
  -- Volume up has limit of 100%
  -- Requires playerctl
  --#############################
  --## WINDOWS AND WORKSPACES ###
  --#############################
  -- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
  -- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
  -- Ignore maximize requests from apps. You'll probably like this.
  -- Fix some dragging issues with XWayland
  -- Windows that I want as pop-up floats
  -- pulseaudio always opens small. Increase it
  -- Override opacity to full (1.0) for certain apps IN certain scenarios
})
